"""Entry point for the bundled deface CLI.

This small wrapper mirrors the console_script generated by pip for the
`deface` package, but is built by PyInstaller so it uses the same
embedded Python runtime as the GUI application.
"""

import sys

from deface.deface import main as deface_main


def _patch_argv0_for_windows() -> None:
    """Strip .exe suffix from argv[0] on Windows for compatibility.

    This matches the behavior of the default console_script entry points
    generated by setuptools, which some CLIs rely on for help text.
    """
    if sys.argv and sys.argv[0].endswith(".exe"):
        sys.argv[0] = sys.argv[0][:-4]


def main() -> int:
    _patch_argv0_for_windows()
    return deface_main()


if __name__ == "__main__":
    raise SystemExit(main())


